version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    volumes:
      - .:/app
    ports:
      - "8000:8000"
