version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: citd.pd.lv/project_drklauns
    env_file: .env
