version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: registry.creativeit.biz/drklauns/drklauns/django:latest
    env_file: .env
    command: /gunicorn.sh
    ports:
      - "172.17.42.1:10012:5000"
    volumes:
        - .:/app
