# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160916_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='+371', max_length=25, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_account',
            field=models.CharField(blank=True, max_length=25, verbose_name='Bank Account'),
        ),
    ]
