# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import drklauns.timetable.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('year', models.IntegerField(default=drklauns.timetable.models.this_year, verbose_name='Year')),
                ('month', models.SmallIntegerField(default=drklauns.timetable.models.this_month, verbose_name='Month')),
                ('story', models.TextField(blank=True, verbose_name='Story')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_story_set', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_story_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view_all'),
                'verbose_name_plural': 'Stories',
                'verbose_name': 'Story',
            },
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'default_permissions': ('add', 'change', 'delete', 'view_all', 'change_all'), 'verbose_name': 'Work object', 'verbose_name_plural': 'Work object'},
        ),
    ]
